### ISSUE TITLE
Couldn't transpile multiple input files into one output file

### ISSUE THREAD

**Issue by SekibOmazic** [origin1tech/gulp-traceur-compiler#2]
When using this plugin like this:
```
gulp.task('bundle', function () {
    return gulp.src('./es6/*/*.js')
        .pipe(traceur(true)) 
  // or .pipe(traceur({ modules: 'amd', annotations: true }, true)
        .pipe(gulp.dest('./dist.js'));
});
```
the result is not a single file but the directory 'dist.js' with all files transpiled separately 

NOTICE: The only reason why I merge everything in one file is that I didn't succeed to run jasmine tests in browser when using multiple files. Node.js environment works fine but browser just doesn't like me.
@origin1tech If you know how to get jasmine tests running in browser (e.g. arrow.js and arrow.spec.js) I'd appreciate it very much.

**Comment by origin1tech** [comment]
Note the readme you need only specify the root file so instead of 

```js
return gulp.src('./es6/*/*.js')
```
Should be
```js
return gulp.src('./es6/root.js')
```

Since you're outputting to single file Traceur handles the imports so that they are in order. Otherwise gulp would likely source the globs in the wrong order.

So what the plugin does is pass off the root to Traceur it traverses the tree via the "imports" then outputs the buffer which the plugin then returns into the stream.

If that makes sense.

**Comment by SekibOmazic** [comment]
Thanks for quick response. Unfortunately I don't have one root file. Instead I have a structure like this:
```
-es6
|--src (arrow.js, promise.js, ...)
|--test (arrow.spec.js, promise.spec.js, ...)
```
So it's a bunch of independent files where e.g. arrow.js exports something and arrow.spec.js imports it. 
Right now I dump everything with ```traceur --out dist.js es6/*/*.js``` into the dist.js and use it in my index.html where I run jasmine test.

I'd of course rather have each file transpiled separately (what your plugin does) and load them in browser (what doesn't work for me - but that's my bad).

**Comment by origin1tech** [comment]
K let me think on that a min. Reloading my wrk station of all things...

**Comment by rmilesson** [comment]
Any more on this? I need this exact functionality as well.

**Comment by origin1tech** [comment]
The problem is it goes against how Gulp works in that a glob of files is compiled then sent through the pipe one by one. 

Hence the plugin when it sends its recursion request to the traceur API it has no concept of your original glob.

The other issue is if you pass in the glob to the "include" in (https://github.com/google/traceur-compiler/blob/master/src/node/recursiveModuleCompile.js#L37) then it will get fired for each in the glob because gulp is iterating from gulp.src('./my/**/glob/*');

In this instance Gulp becomes quite sticky. 

My suggestion would be to NOT use single file out, and do one of the following:

1. Don't use gulp-traceur or gulp-traceur-compiler and instead create a task  where you use traceur directly. That way you can pass in the includes directly to tracer subsequently writing out the result. Similar to how you might use Browserify directly the **gulp way** instead of using gulp-browserify.

2. Use gulp-traceur-compiler but NOT in single file mode. Output to a temp directory then using a post taks concat the files output to real dist and clean the temp directory. You may need some sort of recursion utility to get the imports right for gulp-concat. Below is an example of recursing the imports that we use in one specific instance It may be helpful to you.

Keep in mind I would strongly encourage you to use method 1. There's nothing wrong with using the traceur API directly in Gulp. It's just Node after all.

###Crude Imports Recursion

The below has not be heavily tested and caution should be used when implementing it in any production environment.

```js
// filter `import` statements from file.
function filterImports(basePath){
    if(!fs.existsSync(basePath))
        return [];
    var rows = fs.readFileSync(basePath),
        imports = [],
        baseDir = path.dirname(basePath);
    rows = rows.toString().split('\n');
    rows.forEach(function (r) {
        if(/^import/.test(r)){
            // replace multi space w/ single.
            r = r.trim().replace(/\s+/g, ' ');
            // split on space create keys/tokens.
            var keys = r.split(' '),
                idx = keys.indexOf('from'),
                _path = keys[idx +1];
            if(idx !== -1 && _path){
                // remove quotes.
                _path = _path.replace(/('|")/g, '');
                // replace `.` & `.js;`;
                _path = baseDir + _path.replace(/^\./, '').replace(/(\.js;|;)$/, '') + '.js';
                imports.push(_path);
            }
        }
    });
    return imports;
}

// recursively build `import` tree in order.
function recurseImports(basePath, imports, out){
    imports = imports || filterImports(basePath);
    out = out || [];
    imports.forEach(function (i) {
        var _tmp = filterImports(i);
        // if length recurse its tree.
        if(_tmp.length)
            out.concat(recurseImports(i, _tmp, out))
        else
            out.push(i);
    });
    // add initial base path
    // and return collection.
    out.push(basePath);
    return out;
}
```
